### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by tkdchen** [junaruga/rpm-py-installer#103]
Currently, rpkg has still to support Python 2.6 and we need to run tests with Python 2.6. While I'm adding `py26` to tox env list, I found `rpm-py-installer` does not work with Python 2.6. Could you consider to support Python 2.6?

**Comment by junaruga** [comment]
@tkdchen OK, I am going to try to fix the issue to support Python 2.6 next year.
Have a nice year end holiday!

**Comment by junaruga** [comment]
By the way, which RPM version are you using when running the tests with Python 2.6? The version might affect your issue.

**Comment by tkdchen** [comment]
My RPM version `rpm-4.14.0-2.fc27.x86_64`

Traceback is here.

```
  Using cached rpm-py-installer-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    [INFO] Installing...
    [INFO] Created working directory '/tmp/tmpkjNIaO-rpm-py-installer'
    [INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.14.0-release.tar.gz'.
    Traceback (most recent call last):
      File "install.py", line 1069, in <module>
        main()
      File "install.py", line 1064, in main
        app.run()
      File "install.py", line 38, in run
        self.rpm_py.download_and_install()
      File "install.py", line 170, in download_and_install
        top_dir_name = self.downloader.download_and_expand()
      File "install.py", line 339, in download_and_expand
        top_dir_name = self._download_and_expand_from_archive_url()
      File "install.py", line 373, in _download_and_expand_from_archive_url
        Cmd.tar_xzf(tar_gz_file_name)
      File "install.py", line 990, in tar_xzf
        with tarfile.open(tar_gz_file_path) as tar:
    AttributeError: 'TarFile' object has no attribute '__exit__'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
```

Happy new year!

**Comment by junaruga** [comment]
@tkdchen I saw you forked my repository. I guess you might be working for that.
Now I cake back after finishing my task. I can work for rpm-py-installer again.

I will start to fix from this.
