### ISSUE TITLE
Incorrect branch name used when clone from rpm.git

### ISSUE THREAD

**Issue by tkdchen** [junaruga/rpm-py-installer#104]
I got this error in a Jenkins slave machine while provision a test environment. It's running Fedora 25.

```
Collecting rpm-py-installer (from koji->-r /srv/jenkins/workspace/freshmaker/requirements.txt (line 27))
  Using cached rpm-py-installer-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    [INFO] Installing...
    [INFO] Created working directory '/tmp/tmplDPJWe-rpm-py-installer'
    [INFO] Downloading source by git clone. 'branch: origin/master'
    [ERROR] CMD: [git clone -b origin/master --depth=1 https://github.com/rpm-software-management/rpm.git], Return Code: [128] at [/tmp/tmplDPJWe-rpm-py-installer] Stderr: [Cloning into 'rpm'...
    warning: Could not find remote branch origin/master to clone.
    fatal: Remote branch origin/master not found in upstream origin
    ]
    Traceback (most recent call last):
      File "install.py", line 1069, in <module>
        main()
      File "install.py", line 1064, in main
        app.run()
      File "install.py", line 38, in run
        self.rpm_py.download_and_install()
      File "install.py", line 170, in download_and_install
        top_dir_name = self.downloader.download_and_expand()
      File "install.py", line 332, in download_and_expand
        top_dir_name = self._download_and_expand_by_git()
      File "install.py", line 379, in _download_and_expand_by_git
        self._do_git_clone()
      File "install.py", line 416, in _do_git_clone
        Cmd.sh_e(git_clone_cmd)
      File "install.py", line 900, in sh_e
        raise e
    __main__.InstallError: CMD: [git clone -b origin/master --depth=1 https://github.com/rpm-software-management/rpm.git], Return Code: [128] at [/tmp/tmplDPJWe-rpm-py-installer] Stderr: [Cloning into 'rpm'...
    warning: Could not find remote branch origin/master to clone.
    fatal: Remote branch origin/master not found in upstream origin
    ]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Rsuhen/rpm-py-installer/setup.py", line 127, in <module>
        'bdist_wheel': BdistWheelCommand,
      File "/srv/jenkins/workspace/freshmaker/.tox/py27/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Rsuhen/rpm-py-installer/setup.py", line 57, in run
        install_rpm_py()
      File "/tmp/pip-build-Rsuhen/rpm-py-installer/setup.py", line 20, in install_rpm_py
        raise Exception('Command failed: {0}'.format(cmd))
    Exception: Command failed: /srv/jenkins/workspace/freshmaker/.tox/py27/bin/python2.7 install.py
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Rsuhen/rpm-py-installer/
```

I can reproduce this error in a Fedora 27 machine with command `git clone -b origin/master --depth=1 https://github.com/rpm-software-management/rpm.git`. Changing `origin/master` to `master` fixes this issue.

**Comment by junaruga** [comment]
@tkdchen thanks for the report. Let me check it later.
I am very busy until 9th or 10th January.

**Comment by junaruga** [comment]
Did you run `rpm-py-installer` with `GIT_BRANCH`: `origin/master`?
If do that, `GIT_BRANCH`: `master` is correct. Can you try with "master"?

```
    [ERROR] CMD: [git clone -b origin/master --depth=1 https://github.com/rpm-software-management/rpm.git], Return Code: [128] at [/tmp/tmplDPJWe-rpm-py-installer] Stderr: [Cloning into 'rpm'...
    warning: Could not find remote branch origin/master to clone.
```

https://github.com/junaruga/rpm-py-installer/blob/v0.5.0/install.py#L410

https://github.com/junaruga/rpm-py-installer/blob/master/docs/users_guide.md
See `GIT_BRANCH` Value examples.

**Comment by junaruga** [comment]
I tried below cases in my local.

```
$ git clone -b origin/master --depth=1 https://github.com/rpm-software-management/rpm.git
Cloning into 'rpm'...
warning: Could not find remote branch origin/master to clone.
fatal: Remote branch origin/master not found in upstream origin
```

```
$ git clone -b master --depth=1 https://github.com/rpm-software-management/rpm.git
Cloning into 'rpm'...
remote: Counting objects: 550, done.
remote: Compressing objects: 100% (503/503), done.
remote: Total 550 (delta 62), reused 178 (delta 38), pack-reused 0
Receiving objects: 100% (550/550), 1.39 MiB | 666.00 KiB/s, done.
Resolving deltas: 100% (62/62), done.
```

**Comment by junaruga** [comment]
> I can reproduce this error in a Fedora 27 machine with command git clone -b origin/master --depth=1 https://github.com/rpm-software-management/rpm.git. Changing origin/master to master fixes this issue.

Ah you were mentioning here. There is no logic to append "origin" in `install.py`.
You might set an environment variable `GIT_BRANCH` somewhere.

If that is a reason, I will change the environment variable definition from `GIT_BRANCH` to `RPM_PY_GIT_BRANCH` adding the prefix `RPM_PY`, and other environment variables as well.

**Comment by tkdchen** [comment]
@junaruga Do you mean to run `GIT_BRANCH=master pip install rpm-py-installer`

This command fails too

```
Collecting rpm-py-installer
  1 location(s) to search for versions of rpm-py-installer:
  * https://pypi.python.org/simple/rpm-py-installer/
  Getting page https://pypi.python.org/simple/rpm-py-installer/
  Looking up "https://pypi.python.org/simple/rpm-py-installer/" in the cache
  Current age based on date: 147
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 147
  Analyzing links from page https://pypi.python.org/simple/rpm-py-installer/
    Found link https://pypi.python.org/packages/1b/01/dce6e207ad19bf28c93944f16223fa17a433f54aff7ca1946a4716ca5fde/rpm-py-installer-0.4.1.tar.gz#md5=4f81e6995a4e08f851ef52a6ba7b6234 (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.4.1
    Found link https://pypi.python.org/packages/5b/d1/7405f788ef8aa2dbf3adb7d3133d3e316862f1bc704ca3bfb600adf3f2b8/rpm-py-installer-0.2.0.tar.gz#md5=11acd0438aadfc67c17047628dc21f32 (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.2.0
    Found link https://pypi.python.org/packages/66/14/bd5c9f417cfb515bdf6040b3477f043d73265e157cafb8192898ed7eefb1/rpm-py-installer-0.5.0.tar.gz#md5=05e2364515059d1d853d55fbfd198f2c (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.5.0
    Found link https://pypi.python.org/packages/a2/fe/135e703b0f6aff2fab166f9055fa544232d3a2473978b41c60cde2743b81/rpm-py-installer-0.3.0.tar.gz#md5=53699564d20a89d8df1301162e108cc2 (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.3.0
    Found link https://pypi.python.org/packages/cb/ad/f649a4ed375569b578347b730988eab8cadbdaefe933b133a9441a4527bf/rpm-py-installer-0.1.3.tar.gz#md5=5fde1af3e32627ff91f52ad327beb611 (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.1.3
    Found link https://pypi.python.org/packages/cd/b1/b0219b722bd1e7f18bfd93c39e0686db64ffd94b93750594a58ea64326e6/rpm-py-installer-0.3.1.tar.gz#md5=76637abe1cd048a2a65cbe3f6b02eac2 (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.3.1
    Found link https://pypi.python.org/packages/d2/4b/d6b1a750b4b4c72b5e2401c6fe1cff497357bea4bc05601980798d7c2b64/rpm-py-installer-0.4.0.tar.gz#md5=a82a2aed936f6caa27300da3b0ed0b5a (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.4.0
    Found link https://pypi.python.org/packages/e3/16/f0f48ee1b9ba56bcd0e9ff2cd2330f0f043ffa927da88e3b3c6cf21f0a0f/rpm-py-installer-0.4.2.tar.gz#md5=667dbd44417ae2b7ffb52c1c2c28685b (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.4.2
    Found link https://pypi.python.org/packages/f0/6a/e6896af4f346067dcd033d9f8772c4fd63422d30a6430f20a0f1d124da7e/rpm-py-installer-0.5.0.dev1.tar.gz#md5=e380c7005a2720e088ae2e79c379179f (from https://pypi.python.org/simple/rpm-py-installer/), version: 0.5.0.dev1
  Using version 0.5.0 (newest of versions: 0.1.3, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.0)
  Looking up "https://pypi.python.org/packages/66/14/bd5c9f417cfb515bdf6040b3477f043d73265e157cafb8192898ed7eefb1/rpm-py-installer-0.5.0.tar.gz" in the cache
  Current age based on date: 1444580
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 1444580
  Using cached rpm-py-installer-0.5.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/66/14/bd5c9f417cfb515bdf6040b3477f043d73265e157cafb8192898ed7eefb1/rpm-py-installer-0.5.0.tar.gz#md5=05e2364515059d1d853d55fbfd198f2c (from https://pypi.python.org/simple/rpm-py-installer/)
  Running setup.py (path:/tmp/pip-build-NNj8rr/rpm-py-installer/setup.py) egg_info for package rpm-py-installer
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    [INFO] Installing...
    [INFO] Created working directory '/tmp/tmpmfSdKe-rpm-py-installer'
    [INFO] Downloading source by git clone. 'branch: master'
    [ERROR] CMD: [/home/cqi/Virtualenvs/try-rpm-py/bin/python2 setup.py -q build], Return Code: [1] at [/tmp/tmpmfSdKe-rpm-py-installer/rpm/python] Stderr: [rpmmodule.c: In function ‘initModule’:
    rpmmodule.c:424:19: error: ‘RPMFILE_ARTIFACT’ undeclared (first use in this function); did you mean ‘RPMFILE_NOREPLACE’?
         REGISTER_ENUM(RPMFILE_ARTIFACT);
                       ^
    rpmmodule.c:398:61: note: in definition of macro ‘REGISTER_ENUM’
     #define REGISTER_ENUM(val) PyModule_AddIntConstant(m, #val, val)
                                                                 ^~~
    rpmmodule.c:424:19: note: each undeclared identifier is reported only once for each function it appears in
         REGISTER_ENUM(RPMFILE_ARTIFACT);
                       ^
    rpmmodule.c:398:61: note: in definition of macro ‘REGISTER_ENUM’
     #define REGISTER_ENUM(val) PyModule_AddIntConstant(m, #val, val)
                                                                 ^~~
    rpmmodule.c:560:19: error: ‘TR_RPMDB’ undeclared (first use in this function); did you mean ‘H_RPMDB’?
         REGISTER_ENUM(TR_RPMDB);
                       ^
    rpmmodule.c:398:61: note: in definition of macro ‘REGISTER_ENUM’
     #define REGISTER_ENUM(val) PyModule_AddIntConstant(m, #val, val)
                                                                 ^~~
    error: command 'gcc' failed with exit status 1
    ]
    Traceback (most recent call last):
      File "install.py", line 1069, in <module>
        main()
      File "install.py", line 1064, in main
        app.run()
      File "install.py", line 38, in run
        self.rpm_py.download_and_install()
      File "install.py", line 173, in download_and_install
        self.installer.run()
      File "install.py", line 489, in run
        raise e
    __main__.InstallError: CMD: [/home/cqi/Virtualenvs/try-rpm-py/bin/python2 setup.py -q build], Return Code: [1] at [/tmp/tmpmfSdKe-rpm-py-installer/rpm/python] Stderr: [rpmmodule.c: In function ‘initModule’:
    rpmmodule.c:424:19: error: ‘RPMFILE_ARTIFACT’ undeclared (first use in this function); did you mean ‘RPMFILE_NOREPLACE’?
         REGISTER_ENUM(RPMFILE_ARTIFACT);
                       ^
    rpmmodule.c:398:61: note: in definition of macro ‘REGISTER_ENUM’
     #define REGISTER_ENUM(val) PyModule_AddIntConstant(m, #val, val)
                                                                 ^~~
    rpmmodule.c:424:19: note: each undeclared identifier is reported only once for each function it appears in
         REGISTER_ENUM(RPMFILE_ARTIFACT);
                       ^
    rpmmodule.c:398:61: note: in definition of macro ‘REGISTER_ENUM’
     #define REGISTER_ENUM(val) PyModule_AddIntConstant(m, #val, val)
                                                                 ^~~
    rpmmodule.c:560:19: error: ‘TR_RPMDB’ undeclared (first use in this function); did you mean ‘H_RPMDB’?
         REGISTER_ENUM(TR_RPMDB);
                       ^
    rpmmodule.c:398:61: note: in definition of macro ‘REGISTER_ENUM’
     #define REGISTER_ENUM(val) PyModule_AddIntConstant(m, #val, val)
                                                                 ^~~
    error: command 'gcc' failed with exit status 1
    ]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NNj8rr/rpm-py-installer/setup.py", line 127, in <module>
        'bdist_wheel': BdistWheelCommand,
      File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-NNj8rr/rpm-py-installer/setup.py", line 57, in run
        install_rpm_py()
      File "/tmp/pip-build-NNj8rr/rpm-py-installer/setup.py", line 20, in install_rpm_py
        raise Exception('Command failed: {0}'.format(cmd))
    Exception: Command failed: /home/cqi/Virtualenvs/try-rpm-py/bin/python2 install.py
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NNj8rr/rpm-py-installer/
Exception information:
Traceback (most recent call last):
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/cqi/Virtualenvs/try-rpm-py/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NNj8rr/rpm-py-installer/
```

**Comment by tkdchen** [comment]
I'm curious why need to switch to an branch explicitly. Meanwhile, I also think it would be better add an optional to `setup.py install` command instead of using environment variable, for example `python setup.py install --rpm-branch=master`, and then this option can be passed from `pip` like this `pip install --install-option="--rpm-branch=master"`. That should be easy to work with tox than environment variable.

**Comment by junaruga** [comment]
Thanks for the report. Humm, this time another build error in the report.
Maybe I have to fix several issues step by step. I have some plans to fix those.

> I'm curious why need to switch to an branch explicitly. Meanwhile, I also think it would be better add an optional to setup.py install command instead of using environment variable, for example python setup.py install --rpm-branch=master, and then this option can be passed from pip like this pip install --install-option="--rpm-branch=master". That should be easy to work with tox than environment variable.

The branch option is really for optional use.
Normally without the branch, `rpm-py-installer` installs same version's RPM Python binding with system rpm.

For example, the system RPM version is 4.14.0, `rpm-py-installer` installs the Python binding 4.14.0.
But the case I am considering is if the Python binding 4.14.0 has a bug and people want to use the latest version of 4.14.x. The branch option is used to install the latest version of 4.14.x.

```
$ rpm --version
RPM version 4.14.0
```

> python setup.py install --rpm-branch=master

I did not know the approach. I have to research it.
 
The reason of using environment variable is 

User install "Package A" by `pip install`.
Python Package A
  -> Package A depends on: rpm-py-installer

If this case, is it possible to transfer the branch information `--rpm-branch=master` to `rpm-py-installer`? If do that, the way can be practical.

This environment variable approach is used in `pip`.
I think it is not bad approach. 

https://pip.pypa.io/en/stable/user_guide/
https://github.com/pypa/pip/tree/master/src/pip/_internal
`PIP_CONFIG_FILE`, `PIP_NO_INPUT`.

**Comment by junaruga** [comment]
@tkdchen if you have a time, feel free to send pull-request to fix the issue and other issues. I am happy to review your code.

**Comment by tkdchen** [comment]
I think I know why this happens. Jenkins Git plugin set `GIT_BRANCH` and its value is `origin/master`. An example is https://jenkins.fedorainfracloud.org/job/pyrpkg/Builders=F26/353/console, there is output

```
+ echo origin/master
origin/master
```

> If that is a reason, I will change the environment variable definition from GIT_BRANCH to RPM_PY_GIT_BRANCH adding the prefix RPM_PY, and other environment variables as well.

This should be a good solution to fix this issue I think.

**Comment by junaruga** [comment]
@tkdchen Yeah, that looks the reason of the issue.

**Comment by junaruga** [comment]
@tkdchen can I close ticket? Was this issue fixed on your environment?

**Comment by tkdchen** [comment]
@junaruga Yes. 👍
