### ISSUE TITLE
Fail to install in virtualenv created with Python 2.6

### ISSUE THREAD

**Issue by tkdchen** [junaruga/rpm-py-installer#113]
I got error

```
        self.setup_py.apply_and_save()
    
      File "install.py", line 299, in apply_and_save
    
        with open(self.IN_PATH) as f_in:
    
    IOError: [Errno 2] No such file or directory: 'setup.py.in'
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-CsPrVe/rpm-py-installer/setup.py", line 128, in <module>
    
        'bdist_wheel': BdistWheelCommand,
```

excerpted from output from this command

```
docker run --rm -i -t centos:6 /bin/bash -c "yum install -y epel-release
yum install -y python-virtualenv python-devel gcc rpm-devel redhat-rpm-config
cd
virtualenv try-rpm-py
. ./try-rpm-py/bin/activate
pip install rpm-py-installer
deactivate
"
```

**Comment by junaruga** [comment]
Could you tell me your system CentOS6's system RPM version?

Maybe you can see it running below command

```
RPM_PY_VERBOSE=true pip install -vvv rpm-py-installer
```

instead of

```
pip install rpm-py-installer
```
?

I think this issue is same for https://github.com/junaruga/rpm-py-installer/issues/86 .

I was considering if `rpm-py-installer` has needs for CentOS6, and it would support CentOS6.
I think now it's time.

**Comment by tkdchen** [comment]
Sorry. The RPM version is `4.8.0`

```
[INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.8.0-release.tar.gz'.
```

**Comment by tkdchen** [comment]
This should duplicate #86 . And `0.6.0` works fine with Python 2.6 in my Fedora 27 system. Feel free to close this issue. :)

**Comment by junaruga** [comment]
okay I close this ticket.
