### ISSUE TITLE
Integration test failed

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#124]
The integration test is being failed today and yesterday.
https://travis-ci.org/junaruga/rpm-py-installer/jobs/367590247

```
[INFO] Installing...
Traceback (most recent call last):
  File "/build/install.py", line 1158, in <module>
    main()
  File "/build/install.py", line 1153, in main
    app.run()
  File "/build/install.py", line 29, in run
    self._verify_system_status()
  File "/build/install.py", line 125, in _verify_system_status
    raise InstallError(message)
__main__.InstallError: 
RPM Python binding on system Python should be installed manually.
Install the proper RPM package of python{,2,3}-rpm.
```

**Comment by junaruga** [comment]
The real reason is the uninstall was failed in below code.

```
_uninstall_rpm_py(python_path)
```

```
CMD: /usr/bin/python3 -m pip uninstall -y rpm-python
Cannot uninstall 'rpm-python'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by junaruga** [comment]
From below commit (pip >= v10.0.0), pip can not remove the package installed by distutils.

https://github.com/pypa/pip/commit/fabb73971e14305db720034219577e8f7e4fa8f8

```
commit fabb73971e14305db720034219577e8f7e4fa8f8
Author: Donald Stufft <donald@stufft.io>
Date:   Mon Mar 20 10:18:41 2017 -0400

    Remove the ability to uninstall distutils installed projects
```
