### ISSUE TITLE
Installation with RPM_PY_INSTALL_BIN=true does not work on py34 and py35

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#152]
The installed `rpm` is not shown by `pip list` on py35 and py34.
This works on py36.

## Case: py35 with RPM_PY_INSTALL_BIN=true

It does not work.

```
$ /usr/local/python-3.5.2/bin/python3 -m venv ./venv35

$ source venv35/bin/activate

(venv35) $ RPM_PY_INSTALL_BIN=true RPM_PY_VERBOSE=true python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"
```

```
(venv35) $ ls venv35/lib/python3.5/site-packages/
easy_install.py  pip-8.1.1.dist-info/  __pycache__/  setuptools/
pip/             pkg_resources/        rpm/          setuptools-20.10.1.dist-info/

(venv35) $ ls venv35/lib/python3.5/site-packages/rpm
__init__.py   _rpmb.cpython-36m-x86_64-linux-gnu.so*  _rpms.cpython-36m-x86_64-linux-gnu.so*
__pycache__/  _rpm.cpython-36m-x86_64-linux-gnu.so*   transaction.py
...
```

`rpm` is not shown in the list of the packages.

```
(venv35) $ pip list
pip (8.1.1)
setuptools (20.10.1)
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Failed to import.

```
(venv35) $ python -c 'import rpm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jaruga/git/rebase-helper/venv35/lib/python3.5/site-packages/rpm/__init__.py", line 38, in <module>
    from rpm._rpm import *
ImportError: No module named 'rpm._rpm'
```

## Case: py35 without RPM_PY_INSTALL_BIN=true

It works.

That is the installation from the source code.

```
(venv35_from_src) $ RPM_PY_VERBOSE=true python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"
```

```
(venv35_from_src) $ ls venv35_from_src/lib/python3.5/site-packages
easy-install.pth  pip-8.1.1.dist-info/  rpm-4.14.1-py3.5-linux-x86_64.egg/
easy_install.py   pkg_resources/        setuptools/
pip/              __pycache__/          setuptools-20.10.1.dist-info/

(venv35_from_src) $ ls venv35_from_src/lib/python3.5/site-packages/rpm-4.14.1-py3.5-linux-x86_64.egg/
EGG-INFO/  rpm/

(venv35_from_src) $ ls venv35_from_src/lib/python3.5/site-packages/rpm-4.14.1-py3.5-linux-x86_64.egg/rpm/__init__.py                              _rpm.py
__pycache__/                             _rpms.cpython-35dm-x86_64-linux-gnu.so*
_rpmb.cpython-35dm-x86_64-linux-gnu.so*  _rpms.py
_rpmb.py                                 transaction.py
_rpm.cpython-35dm-x86_64-linux-gnu.so*
```

`rpm` is shown in the list of the packages.

```
(venv35_from_src) $ pip list
pip (8.1.1)
rpm (4.14.1)
setuptools (20.10.1)
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

It works.

```
(venv35_from_src) $ python -c "import rpm; print(rpm.__version__)"
4.14.1
```

## Case: py36 with RPM_PY_INSTALL_BIN=true

It works.

```
$ python3 -m venv ./venv36
$ source venv36/bin/activate
RPM_PY_INSTALL_BIN=true RPM_PY_VERBOSE=true python -c "$(curl -fsSL https://raw.githubusercontent.com/junaruga/rpm-py-installer/master/install.py)"

(venv36) $ pip list
Package    Version
---------- -------
pip        9.0.3--
setuptools 39.0.1-
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv36) $ python -c "import rpm; print(rpm.__version__)"
4.14.1

$ cp -p /usr/lib64/python3.6/site-packages/rpm-4.14.1-py3.6.egg-info venv36/lib/python3.6/site-packages/

(venv36) $ pip list
Package    Version
---------- -------
pip        9.0.3--
rpm        4.14.1-
setuptools 39.0.1-
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv36) $ python -c "import rpm; print(rpm.__version__)"
4.14.1
```

**Comment by junaruga** [comment]
Comparing with `python3-rpm` RPM package.

```
$ rpm -ql python3-rpm
...
/usr/lib64/python3.6/site-packages/rpm
/usr/lib64/python3.6/site-packages/rpm-4.14.1-py3.6.egg-info
/usr/lib64/python3.6/site-packages/rpm/__init__.py
/usr/lib64/python3.6/site-packages/rpm/__pycache__
/usr/lib64/python3.6/site-packages/rpm/__pycache__/__init__.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/rpm/__pycache__/__init__.cpython-36.pyc
/usr/lib64/python3.6/site-packages/rpm/__pycache__/transaction.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/rpm/__pycache__/transaction.cpython-36.pyc
/usr/lib64/python3.6/site-packages/rpm/_rpm.cpython-36m-x86_64-linux-gnu.so
/usr/lib64/python3.6/site-packages/rpm/_rpmb.cpython-36m-x86_64-linux-gnu.so
/usr/lib64/python3.6/site-packages/rpm/_rpms.cpython-36m-x86_64-linux-gnu.so
/usr/lib64/python3.6/site-packages/rpm/transaction.py
```

I copied the egg-info file.

```
$ cp -p /usr/lib64/python3.6/site-packages/rpm-4.14.1-py3.6.egg-info venv35/lib/python3.5/site-packages/
```

Then `rpm` was shown in the result of `pip list`.
But error to import `rpm`.

```
(venv35) $ pip list
pip (8.1.1)
rpm (4.14.1)
setuptools (20.10.1)
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv35) $ python -c "import rpm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jaruga/git/rebase-helper/venv35/lib/python3.5/site-packages/rpm/__init__.py", line 38, in <module>
    from rpm._rpm import *
ImportError: No module named 'rpm._rpm'
```

**Comment by junaruga** [comment]
I renamed like this.

```
$ cd env35/lib/python3.5/site-packages
$ mv rpm-4.14.1-py3.6.egg-info rpm-4.14.1-py3.5.egg-info
```

```
$ cd venv35/lib/python3.5/site-packages/rpm
$ mv _rpmb.cpython-36m-x86_64-linux-gnu.so _rpmb.cpython-35m-x86_64-linux-gnu.so
$ mv _rpm.cpython-36m-x86_64-linux-gnu.so _rpm.cpython-35m-x86_64-linux-gnu.so
$ mv _rpms.cpython-36m-x86_64-linux-gnu.so _rpms.cpython-35m-x86_64-linux-gnu.so
```

But it still does not work.

```
(venv35) $ python -c 'import rpm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jaruga/git/rebase-helper/venv35/lib/python3.5/site-packages/rpm/__init__.py", line 38, in <module>
    from rpm._rpm import *
ImportError: No module named 'rpm._rpm'
```

**Comment by junaruga** [comment]
Talking with Python people in Flock 2018 event, I realized that Python 3.4 or 3.5 could not use the binary built by Python 3.6.
