### ISSUE TITLE
RPM Python binding on system Python should be installed manually.

### ISSUE THREAD

**Issue by jpopelka** [junaruga/rpm-py-installer#160]
```
$ docker run -ti fedora:28 bash -c "dnf install -y python2-pip && pip2 install rpm-py-installer"
Collecting rpm-py-installer
  Downloading https://files.pythonhosted.org/packages/6f/47/d7f5a2cd4977d517edc49f794b5f72cdf966240f7ef9abcf0e8acc0b02df/rpm-py-installer-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    [INFO] Installing...
    Traceback (most recent call last):
      File "install.py", line 1678, in <module>
        main()
      File "install.py", line 1673, in main
        app.run()
      File "install.py", line 31, in run
        self.linux.verify_system_status()
      File "install.py", line 1008, in verify_system_status
        raise InstallError(message)
    __main__.InstallError:
    RPM Python binding on system Python should be installed manually.
    Install the proper RPM package of python{,2,3}-rpm.
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Zo2zlg/rpm-py-installer/setup.py", line 128, in <module>
        'bdist_wheel': BdistWheelCommand,
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Zo2zlg/rpm-py-installer/setup.py", line 57, in run
        install_rpm_py()
      File "/tmp/pip-build-Zo2zlg/rpm-py-installer/setup.py", line 20, in install_rpm_py
        raise Exception('Command failed: {0}'.format(cmd))
    Exception: Command failed: /usr/bin/python2 install.py
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Zo2zlg/rpm-py-installer/
```

**Comment by junaruga** [comment]
> RPM Python binding on system Python should be installed manually.
 > Install the proper RPM package of python{,2,3}-rpm.

Thank you for the report.
The message in the log shows the reason.
Maybe you tried to install RPM Python binding on /usr/bin/python*, right?

In this case, I would recommend to install `dnf install python{,2,3}-rpm`.

**Comment by jpopelka** [comment]
Aha, that's it. Thanks !
You close this if you want.

**Comment by jpopelka** [comment]
[I hit this again](https://github.com/packit-service/packit/pull/84) when I tried the following on centos-7

```
yum -y install epel-release && yum -y install python36-pip && pip3.6 install rpm_py_installer
```

It took me some time to realize that I need to also run `pip3.6 install rpm`

**Comment by jpopelka** [comment]
This can be closed I think.

**Comment by junaruga** [comment]
> It took me some time to realize that I need to also run pip3.6 install rpm.
> 
> EDIT: Which did not help, because what I need is python36-rpm, which does not exist.

Oh you could run "pip3.6 install rpm"?
Right now the `rpm` is just reserved as dummy.

https://pypi.org/project/rpm/

> Right now, this package just reserves the rpm name on PyPI to avoid the potential for a name conflict with the python2-rpm and python3-rpm Python bindings on RPM-based Linux distros.

> EDIT: Which did not help, because what I need is python36-rpm, which does not exist.

Also no `python3-rpm` right?

I think maybe `rpm-py-installer` should provide the option to install it to system Python.
