### ISSUE TITLE
Install fails due to failed download rpm from archive

### ISSUE THREAD

**Issue by mon28** [junaruga/rpm-py-installer#242]
Collecting rpm-py-installer
  Downloading https://files.pythonhosted.org/packages/21/37/f557c91ec825ebf4aa1fd0603359c106e70d4b6443a31e5d98f618340178/rpm-py-installer-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rpm_py_installer.egg-info
    writing pip-egg-info/rpm_py_installer.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/rpm_py_installer.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/rpm_py_installer.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'test-requirements.txt'
    no previously-included directories found matching 'tests'
    writing manifest file 'pip-egg-info/rpm_py_installer.egg-info/SOURCES.txt'
    [INFO] Installing...
    [INFO] Created working directory '/tmp/tmpwpok6osn-rpm-py-installer'
    [INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.11.3-release.tar.gz'.
    Traceback (most recent call last):
      File "install.py", line 2211, in <module>
        main()
      File "install.py", line 2206, in main
        app.run()
      File "install.py", line 46, in run
        raise InstallError(message)
    __main__.InstallError: RPM Python binding failed to install with unknown reason.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v34f4w32/rpm-py-installer/setup.py", line 131, in <module>
        'bdist_wheel': BdistWheelCommand,
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-v34f4w32/rpm-py-installer/setup.py", line 57, in run
        install_rpm_py()
      File "/tmp/pip-build-v34f4w32/rpm-py-installer/setup.py", line 20, in install_rpm_py
        raise Exception('Command failed: {0}'.format(cmd))
    Exception: Command failed: /data/mtare/ipa-v2-document-trainer/document-trainer/venv/bin/python install.py

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v34f4w32/rpm-py-installer/

**Comment by mon28** [comment]
Turns out I was missing python3-devel on my system. Spent the whole day figuring this out and nothing mentioned so far had helped. 
Putting this out there for anyone who gets stuck with the same issue.

Centos 7
python 3.6
rpm 4.11.3
latest pip and setuptools
systems libraries mandatory for this are: python3-rpm, rpm-devel and python3-devel
install: yum install python3-rpm rpm-devel python3-devel

**Comment by junaruga** [comment]
I am sorry for a lack of the error message for you spending whole day about it.

**Comment by junaruga** [comment]
I think python3-rpm and rpm-devel are not required to run `pip install rpm-py-installer`. If  rpm-devel is installed, it is used in more reliable manner. But python3-devel is required mostly because we need to build the RPM building with the C extensions in the most case.

Here is the page related to this topic.
https://github.com/junaruga/rpm-py-installer/blob/master/docs/users_guide.md
Q2. What are the RPM dependencies for rpm-py-installer?
