### ISSUE TITLE
RPM project to drop the `python/setup.py.in`.

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#259]
Here is an important note for this project. The pull-request https://github.com/rpm-software-management/rpm/pull/2231 suggests

* The `python/setup.py.in` to be dropped.
* The `python/rpm.egg-info.in` to be added.

If this PR will be merged, we need to think how to create the RPM pip package without the `python/setup.py.in`.

**Comment by thrix** [comment]
Hi, will this resolve this problem?

```
❯ pip install --use-pep517 rpm-py-installer==1.2.0
Looking in indexes: https://repository.engineering.redhat.com/nexus/repository/pypi.org/simple
Collecting rpm-py-installer==1.2.0
  Using cached https://repository.engineering.redhat.com/nexus/repository/pypi.org/packages/rpm-py-installer/1.2.0/rpm-py-installer-1.2.0.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running egg_info
      writing rpm_py_installer.egg-info/PKG-INFO
      writing dependency_links to rpm_py_installer.egg-info/dependency_links.txt
      writing top-level names to rpm_py_installer.egg-info/top_level.txt
      reading manifest file 'rpm_py_installer.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'test-requirements.txt'
      no previously-included directories found matching 'tests'
      adding license file 'LICENSE'
      writing manifest file 'rpm_py_installer.egg-info/SOURCES.txt'
      [INFO] Installing...
      [INFO] Created working directory '/tmp/tmpf5k2yvrl-rpm-py-installer'
      [INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.18.0-release.tar.gz'.
      Traceback (most recent call last):
        File "/tmp/pip-install-_9x1rczg/rpm-py-installer_34bf97bafc464277a718066361176702/install.py", line 2224, in <module>
          main()
        File "/tmp/pip-install-_9x1rczg/rpm-py-installer_34bf97bafc464277a718066361176702/install.py", line 2219, in main
          app.run()
        File "/tmp/pip-install-_9x1rczg/rpm-py-installer_34bf97bafc464277a718066361176702/install.py", line 46, in run
          raise InstallError(message)
      __main__.InstallError: RPM Python binding failed to install with unknown reason.
      Traceback (most recent call last):
        File "/var/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-framework-RiNn8smE-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/var/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-framework-RiNn8smE-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/var/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-framework-RiNn8smE-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 94, in <module>
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2zlp7y51/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "<string>", line 57, in run
        File "<string>", line 20, in install_rpm_py
      Exception: Command failed: /var/home/mvadkert/.cache/pypoetry/virtualenvs/gluetool-modules-framework-RiNn8smE-py3.9/bin/python install.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
 
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
 
note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by thrix** [comment]
We are now hitting this always on Fedora37 while installing `rpm-py-installer` :( Seems `--use-pep-517` is now the default

**Comment by thrix** [comment]
FTR, filed as #260, seems it is another issue

**Comment by junaruga** [comment]
Thanks for the reporting. Hmm, how to fix this issue..

**Comment by junaruga** [comment]
Perhaps we can have the own `python/setup.py.in` in this repository and apply it.

**Comment by junaruga** [comment]
@nforro My idea is to include the `setup.py.in` in the rpm-py-installer package (`rpm-py-installer-*.tar.gz`). And in the process of running the `install.py`, if the original RPM source doesn't include or in the RPM specific versions (>= N.N.N), set the `setup.py.in`. But I don't know how the pip package can include a file in the package. Do you know how to do? What do you think?

**Comment by junaruga** [comment]
I just executed the CI on the latest master branch.
The result: https://github.com/junaruga/rpm-py-installer/actions/runs/3498835421
The opensuse_tumbleweed is failing, and Fedora 37 is not added on the CI. Yeah Fedora 37 was just released recently.

**Comment by junaruga** [comment]
Just note. The code below shows that we can access a file by specifying the relative path in the pip package. My guess is that we can just include the `setup.py.in` in the rpm-py-installer pip package, and access it by the relative path. 

https://github.com/junaruga/rpm-py-installer/blob/9448ab6d793409feb6236a32e521b7e15b005505/setup.py#L17-L18

**Comment by nforro** [comment]
Exactly, just place it in [`data_files`](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files).

**Comment by junaruga** [comment]
OK. Thanks for the info.

Checking the rpms/rpm rawhide and Fedora 37, the used RPM version is 4.18.0.
https://src.fedoraproject.org/rpms/rpm

The `setup.py.in` still exists in rpm version 4.18.0. I was still misunderstanding that the issue comes from a lack of the `setup.py.in` file. But I was wrong.
https://github.com/rpm-software-management/rpm/commit/0f13fd37d2f182ad3cd237fb4d32c56314bf94ca
https://github.com/rpm-software-management/rpm/tree/rpm-4.18.0-release/python
