### ISSUE TITLE
Cannot install with pip 23.1 (bdist_wheel behavior change)

### ISSUE THREAD

**Issue by rohanpm** [junaruga/rpm-py-installer#276]
rpm-py-installer became uninstallable with pip 23.1.  This seems to be due to the following change mentioned in the pip 23.1 changelog: https://pip.pypa.io/en/stable/news/#v23-1

> Remove setup.py install fallback when building a wheel failed for projects without pyproject.toml. ([#8368](https://github.com/pypa/pip/issues/8368))

### Steps to reproduce

```
$ virtualenv ~/clean-env
created virtual environment CPython3.11.2.final.0-64 in 141ms
  creator CPython3Posix(dest=/home/rmcgover/clean-env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(extra_search_dir=/usr/share/python-wheels,download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/rmcgover/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.6.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

$ . ~/clean-env/bin/activate

(clean-env) $ pip install pip==23.1
Collecting pip==23.1
  Downloading pip-23.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-23.1

(clean-env) $ pip install rpm-py-installer
Collecting rpm-py-installer
  Using cached rpm-py-installer-1.2.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rpm-py-installer
  Building wheel for rpm-py-installer (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rwp295ut/rpm-py-installer_7082f2e96ca0418fadeafe6e48c32bc1/setup.py", line 94, in <module>
          setuptools.setup(
        File "/home/rmcgover/clean-env/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rmcgover/clean-env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/rmcgover/clean-env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/rmcgover/clean-env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/rmcgover/clean-env/lib/python3.11/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/rmcgover/clean-env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-rwp295ut/rpm-py-installer_7082f2e96ca0418fadeafe6e48c32bc1/setup.py", line 91, in run
          raise Exception('bdist_wheel is not supported')
      Exception: bdist_wheel is not supported
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rpm-py-installer
  Running setup.py clean for rpm-py-installer
Failed to build rpm-py-installer
ERROR: Could not build wheels for rpm-py-installer, which is required to install pyproject.toml-based projects
```

### Actual behavior

Installation command fails, as in above example.

### Expected behavior

Installation command succeeds.

### Additional info

Installing with older versions of pip works, but it does generate a related warning:

> DEPRECATION: rpm-py-installer was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 23.1 will enforce this behaviour change. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368

Also, for users running into this issue with tox.  virtualenv v20.21.1 increased the bundled version of pip to 23.1 (see: https://virtualenv.pypa.io/en/latest/changelog.html#v20-21-1-2023-04-19 ).  In some cases then, to work around the issue, just installing an older pip is not enough - one must do for example `pip install tox 'virtualenv<20.21.1'`.

**Comment by lgammo** [comment]
Hello,

This failure is now a blocking issue for our manufacturing system. I cannot update the software. Is there a plan to release an update that addresses this issue any time soon?

Thanks, your help is appreciated.

**Comment by nforro** [comment]
Hi, I'm afraid this requires significant code changes and I don't think there is a plan to release an update, certainly not any time soon. I'm curious, what is your use case for rpm-py-installer?
