### ISSUE TITLE
Supressing mistaken [ERROR] log in sh_e method

### ISSUE THREAD

**Issue by junaruga** [junaruga/rpm-py-installer#91]
Right now `sh_e` method outputs always error log ([ERROR])if the subprocess command returns non zero.
But it is actually not error. It is used to check that a RPM exists in target environment.
According to below case, the actual reason is because `dnf download package` returns zero and does not download the RPM file. 

Will change to outputs [ERROR] conditionally, or not to output it.

> https://travis-ci.org/junaruga/rebase-helper/jobs/283526412

```
    [INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.14.0-rc2.tar.gz'.
    [ERROR] CMD: [/usr/bin/rpm --query rpm-devel --quiet], Return Code: [1] at [/tmp/tmpCVtZb7-rpm-py-installer/rpm-rpm-4.14.0-rc2/python] Stderr: []
    [ERROR] CMD: [/usr/bin/rpm --query popt-devel --quiet], Return Code: [1] at [/tmp/tmpCVtZb7-rpm-py-installer/rpm-rpm-4.14.0-rc2/python] Stderr: []
    [ERROR] CMD: [/usr/bin/rpm --query rpm-devel --quiet], Return Code: [1] at [/tmp/tmpCVtZb7-rpm-py-installer/rpm-rpm-4.14.0-rc2/python] Stderr: []
    Traceback (most recent call last):
      File "install.py", line 1069, in <module>
        main()
      File "install.py", line 1064, in main
        app.run()
      File "install.py", line 38, in run
        self.rpm_py.download_and_install()
      File "install.py", line 173, in download_and_install
        self.installer.run()
      File "install.py", line 487, in run
        raise InstallError(message)
    __main__.InstallError:
    Install failed without rpm-devel package by below reason.
    Can you install the RPM package, and run this installer again?
    PRM file not found.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-I1Trmr/rpm-py-installer/setup.py", line 127, in <module>
        'bdist_wheel': BdistWheelCommand,
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-I1Trmr/rpm-py-installer/setup.py", line 57, in run
        install_rpm_py()
      File "/tmp/pip-build-I1Trmr/rpm-py-installer/setup.py", line 20, in install_rpm_py
        raise Exception('Command failed: {0}'.format(cmd))
    Exception: Command failed: /build/.tox/py2/bin/python2 install.py
```

**Comment by junaruga** [comment]
Always display CMD changing the log level from debug -> info?
And add option argument show_error_log or something like this as default=true to `sh_e`?
